blank_issues_enabled: false
contact_links:
  - name: FireHub Community Support
    url: https://github.com/orgs/The-FireHub-Project/discussions/categories/q-a
    about: Please ask and answer questions here.