name: ☎ Incident
description: Have an incident while using FireHub?
title: "[Incident] : "
labels: ['type: Incident', 'status: Waiting Triage']
body:
  - type: dropdown
    id: platform
    attributes:
      label: On which platform you had incident?
      options:
        - FireHub Core
        - FireHub Skeleton
    validations:
      required: true
  - type: checkboxes
    id: exist
    attributes:
      label: Have you searched the existing incidents?
      description: Please search to see if an question already exists in discussions on [Incidents](https://github.com/orgs/The-FireHub-Project/discussions/categories/incident/).
      options:
        - label: Yes, I have searched the existing question on the discussions on [Incidents](https://github.com/orgs/The-FireHub-Project/discussions/categories/incident/)
          required: true
  - type: textarea
    attributes:
      label: Describe your incident
      description: A clear and concise description of your incident.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Windows 10
          - **Web Browser**: Google Chrome 91.0.4472.124
      value: |
        - OS:
        - Web Browser:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false